### ISSUE TITLE
ro-chrbbidjagh

### ISSUE THREAD

**Issue by robteare** [david-allison/manx-search-data#954]
should be: "created": "1900-04-07",
Committed already - so can't change myself

**Comment by david-allison** [comment]
Link: https://github.com/david-allison/manx-search-data/tree/3d1e69ee28ddf677606ce7c01f63237085b6aed7/OpenData/secular%20printed%20material%20-%201900%20-%201921/Ro-Chribbidjagh

Need to confirm on newspapers
